## This file was auto-generated by CloudCoreo CLI
## This file was automatically generated using the CloudCoreo CLI
##
## This config.rb file exists to create and maintain services not related to compute.
## for example, a VPC might be maintained using:
##
## coreo_aws_vpc_vpc "my-vpc" do
##   action :sustain
##   cidr "12.0.0.0/16"
##   internet_gateway true
## end
##
coreo_aws_advisor_alert "check-ec2-sizes" do
  action :define
  service :ec2
  description "check if size is higher than 8GB"
  id_map "object.snapshot_set.snapshot_id"
  objectives ["snapshots", "snapshots"]
  level "medium"
  audit_objects ["snapshot_set.volume_size", "snapshot_set.encrypted"]
  operators [">", "=="]
  alert_when [8, true]
end
coreo_aws_advisor_ec2 "advise-ec2" do
  action :advise
  region "us-east-1"
  alerts ["check-ec2-sizes"]
end